### PR TITLE
Feature/temporal data

### PR DESCRIPTION
**Pull request by Marius1311**
Adds a tutorial showcasing how CellRank interfaced with moscot to analyze time-course data.

### CODE REVIEW

**Comment by michalk8** [comment]
@Marius1311 generally, would prefer these 2 things:
- name the files as `100_initial_terminal.ipynb` or `200_experimental_time.ipynb` so that globs will sort it by their name
- when adding additional resources (such as images), also prefix them with `100_`, so that we know to which tutorials they belong.

**Comment by Marius1311** [comment]
<p>mh, ok, after the last review, I thought you wanted to have this message all the way to the top. Again, I would have to change this for all tutorials. Can be done on a separate PR. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/64/discussion/#comment-1588279493'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>ok, changed that. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/64/discussion/#comment-1588285771'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>ok. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/64/discussion/#comment-1588279509'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>ok, fixed both. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/64/discussion/#comment-1588279520'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>We know it improves the accuracy ;)</p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/64/discussion/#comment-1588279524'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>That gives https://github.com/theislab/cellrank/issues/1053</p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/64/discussion/#comment-1588279541'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>ok. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/64/discussion/#comment-1588279553'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>Looks nicer - the color legend is continuous rather than discrete. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/64/discussion/#comment-1588279571'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>done. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/64/discussion/#comment-1588279581'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>ok. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/64/discussion/#comment-1588279588'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>removed the link. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/64/discussion/#comment-1588279593'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>I think I fixed it, should be "scanpy" rather than "sc". </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/64/discussion/#comment-1588279601'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>done. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/64/discussion/#comment-1588279666'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>ok. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/64/discussion/#comment-1588279711'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>ok. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/64/discussion/#comment-1588279734'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>ok, added a half sentence on sparsification. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/64/discussion/#comment-1588279760'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>ok. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/64/discussion/#comment-1588279783'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>ok, good suggestion. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/64/discussion/#comment-1588279814'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>ok. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/64/discussion/#comment-1588279856'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>I'm afraid I don't know how. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/64/discussion/#comment-1588279873'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>good point, found a solution. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/64/discussion/#comment-1588279886'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>done. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/64/discussion/#comment-1588279903'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>ok, done almost all. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/64/discussion/#comment-1588279929'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>done. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/64/discussion/#comment-1588279561'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
