### PR TITLE
Update tutorials

### PR DESCRIPTION
**Pull request by Marius1311**
This updates the two tutorials we already had and adds new one, focused on using CellRank when no RNA velocity information is present.

### CODE REVIEW

**Comment by Marius1311** [comment]
@michalk8, the updating of our two old tutorials is done and waiting for your review. In the meantime, I will start with the new tutorial.

**Comment by michalk8** [comment]
Thanks @Marius1311 , I've left some comments in ReviewNB.

**Review by michalk8 — CHANGES_REQUESTED** [review]
I've left my comments in ReviewNB.

**Comment by Marius1311** [comment]
Thanks Mike! I added a putative link to the external page `https://cellrank.readthedocs.io/en/latest/external.html` - is that correct? Links are checked automatically anyway, aren't they?

**Comment by Marius1311** [comment]
> I've left my comments in ReviewNB.

Thanks! That's a really helpful tool I find.

**Comment by michalk8** [comment]
> Thanks Mike! I added a putative link to the external page https://cellrank.readthedocs.io/en/latest/external.html - is that correct? Links are checked automatically anyway, aren't they?

Not really, because you're still using `latest`, not `stable`.
Links are not checked automatically, not is spell-checking.

**Comment by Marius1311** [comment]
Okay, I re-directed all links to `stable`, but probably missed a few.

**Comment by Marius1311** [comment]
I'm done with all your comments in ReviewNB.

**Comment by Marius1311** [comment]
Just need your help with surpressing these ugly warnings, can't figure out how to do it.

**Comment by michalk8** [comment]
> Just need your help with surpressing these ugly warnings, can't figure out how to do it.

Ok, I will handle it.

**Comment by michalk8** [comment]
Warnings are being filtered now (I've fixed some that we produce), note to self `MatplotlibDeprecationWarning` is a subclass of `UserWarning`.

**Comment by michalk8** [comment]
@Marius1311 please could you stick to using `cellrank` Jupyter kernel? otherwise, tests are broken, see
```pytb
kernel_name = 'py38_devel'

    def get_kernel_spec(self, kernel_name):
        """Returns a :class:`KernelSpec` instance for the given kernel_name.
    
        Raises :exc:`NoSuchKernel` if the given kernel name is not found.
        """
        if not _is_valid_kernel_name(kernel_name):
            self.log.warning("Kernelspec name %r is invalid: %s", kernel_name,
                             _kernel_name_description)
    
        resource_dir = self._find_spec_directory(kernel_name.lower())
        if resource_dir is None:
>           raise NoSuchKernel(kernel_name)
E           jupyter_client.kernelspec.NoSuchKernel: No such kernel named py38_devel
```

**Comment by Marius1311** [comment]
Ok, got it, thanks!

**Comment by Marius1311** [comment]
Hi @michalk8, the `beyond_rna_velocity` is ready for a final round of your review!

**Comment by michalk8** [comment]
Thanks @Marius1311 , will review it shortly.

**Comment by michalk8** [comment]
I've fixed some typos, but apart from that, it's really great, I have no objections. I will go over the rest of the tutorials as well and fix `latest` -> `stable`.

**Pull request merged**
