### PR TITLE
Real time tutorial

### PR DESCRIPTION
**Pull request by Marius1311**
Adds a new tutorial for the external WOT kernel.

### CODE REVIEW

**Comment by Marius1311** [comment]
@michalk8, would be great to hear your input, esp. wrt to the utility functions, which are kind of lengthy and I don't know how to hide them.

**Review by michalk8 — CHANGES_REQUESTED** [review]
Looks pretty neat @Marius1311 !
Re plotting, I'd consider to add the log-odds and? the correlation scatterplot to the main API. If not, I'd just have 1 line docstring.
Re the data: will it be on the figshare?

**Comment by Marius1311** [comment]
Thanks for the review @michalk8! will go over this tomorrow and fix the last bits. I plan to upload the data to figshare.

**Comment by Marius1311** [comment]
All done, just need to integrate the gene sets now and implement the utility functions.

**Comment by Marius1311** [comment]
Hi @michalk8, the wot tutorial is done and ready for a final round of your review! Feel free to add minor changes yourself while I'm going through the other tutorials to update the bibtex links.

**Comment by michalk8** [comment]
@Marius1311 re bibtex: you don't need to put citations in `(...)`, it's done through `bibtex`.

**Comment by Marius1311** [comment]
Bibtex updates done.

**Comment by michalk8** [comment]
Great, I will check if everything renders as it should/no warning and merge after release notes PR is done.

**Pull request merged**
