### PR TITLE
Add a "getting started" tutorial

### PR DESCRIPTION
**Pull request by Marius1311**
This serves as an entry point for CellRank analysis.

### CODE REVIEW

**Comment by Marius1311** [comment]
Note: using the same CellRank commit, this worked in the fate probability tutorial.

**Comment by michalk8** [comment]
> Note: using the same CellRank commit, this worked in the fate probability tutorial.

Can you please check `assert adata is pk.adata` (or `assert g.adata is adata`)? I suspect some copy was made.

**Comment by Marius1311** [comment]
Amazing @michalk8, thank you so much for spotting this!

**Comment by Marius1311** [comment]
<p>I agree with all and adapted all. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/61/discussion/#comment-1577290400'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>done. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/61/discussion/#comment-1577290425'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>I don't remember; I removed it for now. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/61/discussion/#comment-1577290453'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>ok</p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/61/discussion/#comment-1577290479'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>ok, I created some hierachy. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/61/discussion/#comment-1577290503'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>ok, thanks. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/61/discussion/#comment-1577290521'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>great, thanks. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/61/discussion/#comment-1577290557'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>ok. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/61/discussion/#comment-1577290571'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>ok. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/61/discussion/#comment-1577290585'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/61/discussion/#comment-1577290637'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>I think they should remain within their corresponding sections. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/61/discussion/#comment-1577290661'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>thanks for spotting. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/61/discussion/#comment-1577290686'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>ok. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/61/discussion/#comment-1577290708'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>Ok, moved it to the end. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/61/discussion/#comment-1577290727'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>all done, thanks. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/61/discussion/#comment-1577290744'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>all done. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/61/discussion/#comment-1577290766'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>ok. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/61/discussion/#comment-1577290805'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>mh, that I'm not sure about. I'll leave this. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/61/discussion/#comment-1577290821'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>ok, removed everywhere. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/61/discussion/#comment-1577290849'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>I disagree here - I don't think we should overload users with information at the beginning, but cut to the chase quickly, and reserve this info for people who made it all the way through. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/61/discussion/#comment-1577290867'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>Ah, I see what you mean - you're just referring to the note. Ok, that's fine, happy to change that. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/61/discussion/#comment-1577290867'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
<p>done. </p>

---

 <a href='https://app.reviewnb.com/theislab/cellrank_notebooks/pull/61/discussion/#comment-1577290867'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Marius1311** [comment]
Hi @michalk8, I adressed all of your comments, thank you very much for this detailed review. black-nb is failing for some reason and I don't understand why; I'm merging this anyways. I'll go ahead and re-format the other notebooks in the same fashion.

**Pull request merged**
